export type { ElemId, ElemRef, ReplicaId } from "./elem-id.js";
export { compareElemIds, toRef } from "./elem-id.js";
export type { Op } from "./sequence.js";
export { Sequence } from "./sequence.js";
export { NaiveDoc } from "./naive-doc.js";
export type { NaiveOp, NaivePayload } from "./naive-doc.js";
export { ArrayDoc } from "./array-doc.js";
export type { CrdtOp, CrdtPayload, DeletePayload, InsertPayload } from "./array-doc.js";
export { RgaDoc } from "./rga-doc.js";
export { Doc } from "./fugue-doc.js";
export type { Anchor, AnchorSide } from "./fugue-doc.js";
export { decodeOps, decodeOpsStream, decodeOpsStreamPartial, encodeOps } from "./encoding.js";
export type { StateVector } from "./sequence.js";
